<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H2Q1PN9" ignored="0" name="Test" tests="4" failures="1" timestamp="2020-09-01T19:48:14 IST" time="84.906" errors="0">
  <testcase name="displayText" time="13.724" classname="com.framework.testCases.Login"/>
  <testcase name="verifyText" time="3.386" classname="com.framework.testCases.Login">
    <failure type="java.lang.AssertionError" message="expected [somu] but found [Introducing Work.com, a suite of solutions, expertise and resources to help you reopen safely.  ]">
      <![CDATA[java.lang.AssertionError: expected [somu] but found [Introducing Work.com, a suite of solutions, expertise and resources to help you reopen safely.  ]
at com.framework.testCases.Login.verifyText(Login.java:91)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyText -->
  <testcase name="login" time="31.144" classname="com.framework.testCases.Login"/>
  <testcase name="login" time="27.509" classname="com.framework.testCases.Login"/>
</testsuite> <!-- Test -->
